---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - name: Ensure a pod is running.
      k8s_info:
        kind: Pod
        namespace: kube-system
      register: kube_system_pods
      until:
        - kube_system_pods['resources'] is defined
        - kube_system_pods['resources'][0]['status']['phase'] == 'Running'
      delay: 5
      retries: 60
