---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - config.yml

  tasks:
    - name: Clone the operator-sdk-samples project.
      git:
        repo: https://github.com/operator-framework/operator-sdk-samples.git
        version: "{{ operator_samples_version }}"
        dest: ./operator-sdk-samples
        force: true

    - name: Attempt to fix file permissions.
      file:
        dest: ./operator-sdk-samples
        mode: 0777
        # mode: 'u=rwX,g=rX,o=rX'
        recurse: true

    - name: Deploy a memcached DaemonSet so image is pulled to all nodes.
      include_tasks: tasks/memcached-daemonset.yml

    - name: Deploy cert-manager (required for Go operator).
      include_tasks: tasks/cert-manager.yml
      when: "'go' == operator_under_test"

    - name: Deploy prometheus-operator (required for Helm operator).
      include_tasks: tasks/prometheus-operator.yml
      when: "'helm' == operator_under_test"

    - name: Build, deploy, benchmark, and undeploy operators.
      include_tasks: tasks/operator-tasks.yml
      loop: ["{{ operator_under_test }}"]
      loop_control:
        loop_var: operator_type
