---
- name: Set the {{ operator_type }} memcached operator image name.
  set_fact:
    operator_image: "{{ registry }}/{{ image_name }}-{{ operator_type }}:{{ image_tag }}"

- name: Build, push, and deploy the {{ operator_type }} memcached operator.
  command: "{{ item }}"
  args:
    chdir: ./operator-sdk-samples/{{ operator_type }}/memcached-operator
  with_items:
    - make docker-build
    - make docker-push
    - make deploy
  environment:
    IMG: "{{ operator_image }}"
