---
- name: Set the {{ operator_type }} memcached operator image name.
  set_fact:
    operator_image: "{{ registry }}/{{ image_name }}-{{ operator_type }}:{{ image_tag }}"

- name: Set the app label selector for Helm.
  set_fact:
    app_label_selector: app.kubernetes.io/name=memcached
  when: operator_type == 'helm'

- name: Ensure the operator namespace exists.
  k8s:
    name: memcached-operator-system
    api_version: v1
    kind: Namespace
    state: present

- name: Build, push, and deploy the {{ operator_type }} memcached operator.
  shell: "{{ item }}"
  args:
    chdir: ./operator-sdk-samples/{{ operator_type }}/memcached-operator
  with_items:
    # Can't use make for docker-build target because of Go operator test dep.
    - docker build . -t $IMG
    - make docker-push
    - make install
    - make deploy
  environment:
    IMG: "{{ operator_image }}"
    executable: /bin/bash

- name: Wait for Operator Pod to be 'Running'.
  k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - control-plane=controller-manager
    namespace: memcached-operator-system
  register: operator_pod
  failed_when: false
  until: operator_pod.resources[0].status.phase == 'Running'
  delay: 5
  retries: 10

- name: Pause to allow cluster to stabilize.
  pause:
    seconds: 10

- name: Deploy {{ memcached_cr_count }} {{ operator_type }} memcached CRs.
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/memcached-cr.yml.j2') }}"

- name: Wait for {{ memcached_cr_count }} {{ operator_type }} Memcached Pods to be running.
  k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - "{{ app_label_selector }}"
  register: memcached_pods
  until: (memcached_pods.resources | count) == memcached_cr_count
  delay: 5
  retries: 60

- name: Wait for {{ operator_type }} Memcached Pods to be ready.
  command: >
    kubectl wait --for=condition=Ready
    pods --selector {{ app_label_selector }} --timeout=300s
  changed_when: false

# TODO: Kill Operator Pod, benchmark re-reconciliation.
# See: https://github.com/geerlingguy/operator-sdk-performance-testing/issues/4

- name: Undeploy the {{ operator_type }} memcached operator.
  command: make undeploy
  async: 10
  poll: 0
  args:
    chdir: ./operator-sdk-samples/{{ operator_type }}/memcached-operator
  environment:
    IMG: "{{ operator_image }}"
