---
- name: Set the {{ operator_type }} memcached operator image name.
  set_fact:
    operator_image: "{{ registry }}/{{ image_name }}-{{ operator_type }}:{{ image_tag }}"

- name: Build, push, and deploy the {{ operator_type }} memcached operator.
  shell: "{{ item }}"
  args:
    chdir: ./operator-sdk-samples/{{ operator_type }}/memcached-operator
  with_items:
    # Can't use make for docker-build target because of Go operator test dep.
    - docker build . -t $IMG
    - make docker-push
    - make install
    - make deploy
  environment:
    IMG: "{{ operator_image }}"
    executable: /bin/bash

# TODO: Wait for operator to be 'Running'.

# TODO: Create 50 instances and see how long they take to reconcile.

- name: Undeploy the {{ operator_type }} memcached operator.
  command: make undeploy
  args:
    chdir: ./operator-sdk-samples/{{ operator_type }}/memcached-operator
  environment:
    IMG: "{{ operator_image }}"
