---
- name: Download prometheus-operator manifest.
  get_url:
    url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/{{ prometheus_operator_version }}/bundle.yaml
    dest: /tmp/prometheus-operator.yaml
    mode: 0644

# Without this the operator doesn't deploy successfully on the first go.
- name: Manually create the prometheus-operator ServiceAccount.
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        labels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: prometheus-operator
          app.kubernetes.io/version: v0.41.1
        name: prometheus-operator
        namespace: default

- name: Manually create the prometheus ServiceAccount.
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: prometheus
        namespace: default

- name: Manually create the prometheus-operator cluster role
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: prometheus
      rules:
      - apiGroups: [""]
        resources:
        - nodes
        - nodes/proxy
        - nodes/metrics
        - services
        - endpoints
        - pods
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources:
        - configmaps
        verbs: ["get"]
      - apiGroups:
        - networking.k8s.io
        resources:
        - ingresses
        verbs: ["get", "list", "watch"]
      - nonResourceURLs: ["/metrics"]
        verbs: ["get"]

- name: Manually create the prometheus-operator cluster role binding
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: prometheus
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: prometheus
      subjects:
      - kind: ServiceAccount
        name: prometheus
        namespace: default


- name: Deploy prometheus-operator into the cluster.
  k8s:
    state: present
    src: /tmp/prometheus-operator.yaml
    wait: true

- name: Deploy additional-scrape-configs into the cluster.
  k8s:
    state: present
    src: /home/kevinfan/additional-scrape-configs.yaml
    wait: true

- name: Deploy the prometheus CR
  k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: prometheus
        namespace: default
      spec:
        additionalScrapeConfigs:
          key: prometheus-additional.yaml
          name: additional-scrape-configs
        serviceAccountName: prometheus
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        resources:
          requests:
            memory: 400Mi
        scrapeInterval: 1s

# - name: Delete prometheus-operator manifest.
#   file:
#     path: /tmp/prometheus-operator.yaml
#     state: absent
